model:
  name: "openai/whisper-tiny"   
  language: "danish"
  task: "transcribe"
  freeze_encoder: true
  unfreeze_encoder_at_step: 50000 #do not use
  use_lora: false
  lora_r: 32                     
  lora_alpha: 64                 
  lora_dropout: 0.05
  lora_target_modules:           
    - "q_proj"
    - "v_proj"
    - "k_proj"
    - "out_proj"
    - "fc1"
    - "fc2"
  attention_dropout: 0.1        

data:
  dataset_name: "CoRal-project/coral-v2"
  dataset_config: "read_aloud"
  sample_rate: 16000
  streaming: true
  shuffle_buffer: 1000           
  seed: 42
  min_input_length: 0.5          
  max_input_length: 30.0         
  augmentation:
    noise_augmentation: true     
    noise_level: 0.005           
    speed_perturbation: true    

training:
  output_dir: "whisper-tiny-danish"
  batch_size: 8
  grad_accum_steps: 4
  eval_batch_size: 16
  learning_rate: 7.0e-5
  warmup_steps: 1000
  max_steps: 50000
  save_steps: 1000
  eval_steps: 1000
  logging_steps: 50
  generation_max_length: 225
  load_best_model_at_end: true
  metric_for_best_model: "wer"
  greater_is_better: false
  dataloader_num_workers: 4